Add original keymap made by FKML
swanmatch/qmk_firmware pull request #1
Opened 2020-02-01 05:59 UTC by FKML520

I add my keymap based on “swammatch/qmkfirmware” and send to “add silverbullet44”.

2020-02-01 06:25 UTC, swanmatch commented
キーマップありがとー！！！
いま出先で画面ちっちゃくてキーマップよく見えないけど、とりあえず見れる範囲でみましゅ！

2020-02-01 07:20 UTC, swanmatch requested changes
拝啓 創造神さまへ

おめでとう！
このレポジトリの記念すべき最初のプルリクです！！

実は創造神さまがcloneしたあとに本家にプルリク送ったらけちょんけちょんにされました。
そのへんの指摘受けて直したのがadd_silverbullet44ってブランチにいます。

魔王がけちょんけちょんにされている現場はこちらになります。
https://github.com/qmk/qmk_firmware/pull/7950

いずれ本家にマージする際に同様の指摘を受けると思うのだよねー
もともと私のキーマップの不備なので、
めんどかったらこのままマージしたあとおれのほうで直して本家にがっちゃんこするけど、
なんか人のキーマップ勝手にいじってるみたいになっちゃうから、
ここで直しちゃったほうが良い気がするー

masterとadd_silverbullet44の違いは下記コマンドでわかるよん。
git diff master..add_silverbullet44 keyboards/silverbullet44/keymaps/default/

それではよいキーボードライフを！

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/config.h
> +#pragma once
このファイルいらないらしい…

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +/* Copyright 2019 SwanMatch
せっかくだから、ふかめるさんのCopyrightにしてみては?
```suggestion
/* Copyright 2020 FKML
```

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +
消しちゃえー！

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +bool alt_pressed = false;
消しちゃえー！
```suggestion
```

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +        break;
ちょっとちゃんと見れてないんだけど、update_tri_layerとADJUSTのコード両方つかってる？
どっちかでよかったらどっちかにしとくと良いかも。

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> + [_QWERTY] = LAYOUT( \
なんか全体的に行末のバックスラッシュいらないって言われた。。。
(魔王知らなかった)

```suggestion
 [_QWERTY] = LAYOUT(
```

2020-02-01 07:20 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +}
消しちゃえー！

2020-02-01 08:48 UTC, FKML520 commented
拝啓　魔王様

ご丁寧なご指摘ありがとうございます。
当方キィボォド初心者につき大変勉強になりました。

ご指摘いただいた件に関しては全て修正し、ビルドができることも確認致しました。

けちょんけちょんにされても負けるなーがんばれー！

創造神

2020-02-03 01:55 UTC, swanmatch reviewed
さっそく修正ありがとう！
追加でいくつか指摘させていただきましたので、
お手すきの際にご確認いただけますでしょうか。
これ終わったらマージしちゃうべ！

追記:
おとといの帰りの電車、先頭車両に乗ったけど、
カーテン閉めていてあまりおもしろくなかったです。
残念。。。

2020-02-03 01:55 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +  ADJUST,
ADJUSTを使わないようなら消してくれると…！
```suggestion
```

2020-02-03 01:55 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +                             _______, _______, _______, ADJUST,  _______, _______, _______, _______
ADJUSTを使わないようなら消してくれると…！
```suggestion
                             _______, _______, _______, _______,  _______, _______, _______, _______ 
```

2020-02-03 01:55 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +                              _______, _______, _______, _______,   ADJUST, _______, _______, _______
同上～
```suggestion
                              _______, _______, _______, _______,   _______, _______, _______, _______ 
```

2020-02-03 01:55 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +
ごめん、これはこの前の指摘漏れ！
列挙型って言うんだけ？にしとくといいってさ。

```suggestion
enum layer {
    _QWERTY,
    _CURSOL,
    _CALC,
    _ADJUST,
};
```

2020-02-03 01:55 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/readme.md
> +
全体を「```」で囲って、行頭の*とかを消すと見やすくなってオススメ。
参考↓
https://raw.githubusercontent.com/swanmatch/qmk_firmware/add_silverbullet44/keyboards/silverbullet44/keymaps/default/readme.md
https://github.com/swanmatch/qmk_firmware/tree/add_silverbullet44/keyboards/silverbullet44/keymaps/default

2020-02-03 01:55 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +#define XXXXXXX KC_NO
これももうデフォで定義されてるからいらないらしいよ…
便利な世の中になったものだ。
```suggestion
```

2020-02-03 02:00 UTC, swanmatch requested changes
ごめん、もういっこ！

2020-02-03 02:00 UTC, swanmatch commented on keyboards/silverbullet44/keymaps/FKML/keymap.c
> +        case RAISE:
インデント
あと、ここだけインデントが2spaceになってるので
4spaceにしとくと良さそう。

```suggestion
      case RAISE:
```

2020-02-04 12:25 UTC, FKML520 commented
魔王様

追加でいただいてた修正分お待たせいたしました！
修正できましたー。確認お願いいたしますー！！！

カーテン閉まってたのは残念だ…　反射を防ぐために閉めちゃってたのかしらん。

2020-02-05 00:04 UTC, merged

2020-02-05 00:08 UTC, swanmatch commented
かみさま

修正ありがとう！マージしました！
本家マージの前にインデントと行末空白とかだけ
こっちで若干整形するかも～

今後ともSilverBullet44をかわいがってあげてください。

2020-02-05 00:44 UTC, swanmatch commented
ちなみに整形↓の感じです～
https://github.com/swanmatch/qmk_firmware/commit/acfc83d0ebbf5c307c7c1d262a0971653b212bc6#diff-d4b018956f579d6120d071a277b126c6R66

2020-02-05 10:40 UTC, FKML520 commented
魔王さま

やった！まーじ！人(神)生初のまーじです！
整形ありがとうございます。お手間おかけしてすみません。。。

SilverBullet44、めちゃめちゃ可愛がります…！！！！！！ぴこぴこぴこ！